[package]
name = "rust-mal-lib"
version = "0.1.0"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
regex = "1.2.1"
log = "0.4.8"
