[package]
name = "rust-mal-lib-wasm"
version = "0.1.0"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]
edition = "2018"
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
rust-mal-lib = { path = "../rust_mal_lib" }
wasm-bindgen="0.2.56"
